/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GraphicsRouteImport } from './routes/graphics'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ArchitectureIndexRouteImport } from './routes/architecture.index'
import { Route as ArchitectureSlugRouteImport } from './routes/architecture.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRoute = GraphicsRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureIndexRoute = ArchitectureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchitectureRoute,
} as any)
const ArchitectureSlugRoute = ArchitectureSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArchitectureRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRouteWithChildren
  '/contact': typeof ContactRoute
  '/graphics': typeof GraphicsRoute
  '/video': typeof VideoRoute
  '/architecture/$slug': typeof ArchitectureSlugRoute
  '/architecture/': typeof ArchitectureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/graphics': typeof GraphicsRoute
  '/video': typeof VideoRoute
  '/architecture/$slug': typeof ArchitectureSlugRoute
  '/architecture': typeof ArchitectureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRouteWithChildren
  '/contact': typeof ContactRoute
  '/graphics': typeof GraphicsRoute
  '/video': typeof VideoRoute
  '/architecture/$slug': typeof ArchitectureSlugRoute
  '/architecture/': typeof ArchitectureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/contact'
    | '/graphics'
    | '/video'
    | '/architecture/$slug'
    | '/architecture/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/graphics'
    | '/video'
    | '/architecture/$slug'
    | '/architecture'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architecture'
    | '/contact'
    | '/graphics'
    | '/video'
    | '/architecture/$slug'
    | '/architecture/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRouteWithChildren
  ContactRoute: typeof ContactRoute
  GraphicsRoute: typeof GraphicsRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture/': {
      id: '/architecture/'
      path: '/'
      fullPath: '/architecture/'
      preLoaderRoute: typeof ArchitectureIndexRouteImport
      parentRoute: typeof ArchitectureRoute
    }
    '/architecture/$slug': {
      id: '/architecture/$slug'
      path: '/$slug'
      fullPath: '/architecture/$slug'
      preLoaderRoute: typeof ArchitectureSlugRouteImport
      parentRoute: typeof ArchitectureRoute
    }
  }
}

interface ArchitectureRouteChildren {
  ArchitectureSlugRoute: typeof ArchitectureSlugRoute
  ArchitectureIndexRoute: typeof ArchitectureIndexRoute
}

const ArchitectureRouteChildren: ArchitectureRouteChildren = {
  ArchitectureSlugRoute: ArchitectureSlugRoute,
  ArchitectureIndexRoute: ArchitectureIndexRoute,
}

const ArchitectureRouteWithChildren = ArchitectureRoute._addFileChildren(
  ArchitectureRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRouteWithChildren,
  ContactRoute: ContactRoute,
  GraphicsRoute: GraphicsRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
